"use client";
import {useEffect,useState} from 'react';
type UpdateState={status:string;currentVersion:string;version?:string;mode:string;autoCheck:boolean;percent?:number;notes?:string;message?:string;bytes?:number};
type Bridge={updateAction:(action:string,value?:boolean)=>Promise<UpdateState>;onUpdateState:(listener:(state:UpdateState)=>void)=>()=>void};
export function AppUpdates(){
 const [state,setState]=useState<UpdateState|null>(null),[opened,setOpened]=useState(false);
 useEffect(()=>{const api=(window as unknown as {zhuangPrompter?:Bridge}).zhuangPrompter;if(!api?.updateAction)return;void api.updateAction('state').then(setState).catch(()=>{});return api.onUpdateState(setState);},[]);
 if(!state)return null;
 const run=(action:string,value?:boolean)=>{const api=(window as unknown as {zhuangPrompter:Bridge}).zhuangPrompter;void api.updateAction(action,value).then(setState);};
 const titles:Record<string,string>={idle:'检查 App 更新',checking:'正在检查…',current:'已是最新版本',available:'发现新版本',downloading:'正在下载…',downloaded:'更新已下载',error:'更新暂未完成',installing:'正在安装…'};
 return <div className="app-update-root"><button className="app-update-trigger" onClick={()=>setOpened(!opened)}>版本 {state.currentVersion}{state.status==='available'?' · 有更新':''}</button>{opened&&<section className="app-update-panel" aria-label="App 更新"><button className="app-update-close" aria-label="关闭更新面板" onClick={()=>setOpened(false)}>×</button><h2>{titles[state.status]||state.status}</h2><p>当前 v{state.currentVersion}{state.version?` → v${state.version}`:''}</p>{state.notes&&<p style={{whiteSpace:'pre-wrap'}}>{state.notes}</p>}{state.bytes&&<p>{(state.bytes/1024/1024).toFixed(1)} MB</p>}{state.status==='downloading'&&<><progress max={100} value={state.percent||0}/><p>{Math.round(state.percent||0)}%</p><button onClick={()=>run('cancel')}>取消下载</button></>}{state.message&&<p role="status">{state.message}</p>}{['idle','error','current'].includes(state.status)&&<button onClick={()=>run('check')}>检查更新</button>}{state.status==='available'&&<button onClick={()=>run('download')}>下载更新</button>}{state.status==='downloaded'&&<><p>安装前请停止播放，保存稿件并返回首页，关闭其他控制页。</p><button onClick={()=>run('install')}>{state.mode==='in-app-install'?'重启并安装':'打开安装包'}</button>{location.pathname.includes('/control')&&<button onClick={()=>window.dispatchEvent(new Event('prompter-save-and-home'))}>保存并返回首页</button>}{state.mode!=='in-app-install'&&<p>此 Mac 版本需手动替换：退出 App，将安装包内的 App 拖入 Applications。</p>}</>}<label><input type="checkbox" checked={state.autoCheck} onChange={e=>run('auto-check',e.target.checked)}/> 启动时检查更新（不会自动下载或安装）</label></section>}</div>;
}
